### ISSUE TITLE
Stylelint 16 requires exposed ruleName

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/stylelint-plugin-carbon-tokens#107]
Was reviewing a dependency update which updates to [Stylelint 16](https://stylelint.io/migration-guide/to-16/) and caught this during a CI check.

Downgrading Stylelint back to 15.11.0 and Prettier down to 2.8.8 gets our lint passing again.

```
Running audit using: yarn npm audit --environment production --severity moderate
Error: stylelint requires plugins to expose a ruleName. The plugin "/Code/ibm-products/node_modules/stylelint-plugin-carbon-tokens/dist/index.js" is not doing this, so will not work with stylelint. Please file an issue with the plugin.
```

Previously documented in this PR https://github.com/carbon-design-system/ibm-products/pull/4168#pullrequestreview-1863853796.

**Comment by lee-chase** [comment]
This is a bit trickier than first glance @elycheea 

The rules do have rule names but in moving from 15 to 16 stylelint does not interpret the CJS plugin as having them seeing 'default' when looking for rulename
![image](https://github.com/carbon-design-system/stylelint-plugin-carbon-tokens/assets/15086604/93cd83ad-bced-4164-87af-a3c489a8b15a)

As opposed to an ESM module at the same break point
![image](https://github.com/carbon-design-system/stylelint-plugin-carbon-tokens/assets/15086604/b6ba9048-b8d3-43b9-9fc4-02dd29b7569d)

Converting to ESM on the face of it seems simple enough but hits a number of issues.
- Node and as a result Jest only have experimental support for ESM. So it might be necessary to switch to `stylelint-test-rule-node` https://stylelint.io/developer-guide/plugins#testing
- Importing JSON files is also experimental and needs to be reworked.

**Comment by lee-chase** [comment]
@elycheea you are now blocked by a carbon dependency on `stylelint-a11y` perhaps switch to `@double-great/stylelint-a11y`
