### ISSUE TITLE
Review defaults before V3 release

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/stylelint-plugin-carbon-tokens#119]
Review the defaults.

Some functions exported by Carbon should probably be accepted by default e.g. `font-style`

**Comment by wkeese** [comment]
And also `font-weight`, aka `acceptCarbonFontWeightFunction`, see #103.

**Comment by lee-chase** [comment]
As part of 3.0.0-rc.9 removed options in favour of permitting by default

- layout-use -  fluid, container and icon size tokens
- type-use - weight, font family and scale functions

The font-style option was removed in 3.0.0-rc.7 permitting the setting of `font-style` directly. This will be applied to the next v2 release also.
