### ISSUE TITLE
Style lint expects carbon token use for use transform

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/stylelint-plugin-carbon-tokens#31]
# Description 

In my code I am using the following code:
<img width="505" alt="Screen Shot 2021-02-11 at 3 03 07 PM" src="https://user-images.githubusercontent.com/12755042/107692048-40913480-6c7a-11eb-922e-19aef930c9ed.png">
<img width="487" alt="Screen Shot 2021-02-11 at 3 03 31 PM" src="https://user-images.githubusercontent.com/12755042/107692091-4edf5080-6c7a-11eb-8bc0-6db53a6ee450.png">

This is throwing a linting error to use carbon tokens for transform. If the transform is 0 it should not throw the carbon use token error.

<img width="1337" alt="Screen Shot 2021-02-11 at 3 02 07 PM" src="https://user-images.githubusercontent.com/12755042/107691931-1d668500-6c7a-11eb-9abb-34643e42ebca.png">

**Comment by AlexanderMelox** [comment]
I did had an error but changed it to this, but still gives me the stylelint error.
<img width="487" alt="Screen Shot 2021-02-11 at 3 21 56 PM" src="https://user-images.githubusercontent.com/12755042/107694039-e47bdf80-6c7c-11eb-9427-d1e62c062523.png">

**Comment by lee-chase** [comment]
This test passes in V2.

    {
      code: `.foo { transform: translateY(calc(-1 * #{$spacing-05})); }`,
      description: `Accept translateY using  calc(-1 * #{$})`
    }
