### ISSUE TITLE
Unexpected token messages

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/stylelint-plugin-carbon-tokens#42]
The linter is now producing the following messages:

Unexpected token "size-xsmall" found in @carbon/layout - please raise an issue
Unexpected token "size-small" found in @carbon/layout - please raise an issue
Unexpected token "size-medium" found in @carbon/layout - please raise an issue
Unexpected token "size-large" found in @carbon/layout - please raise an issue
Unexpected token "size-xlarge" found in @carbon/layout - please raise an issue
Unexpected token "size-2XLarge" found in @carbon/layout - please raise an issue

This is with @carbon/layout v1.22.10

As these messages ask me to please raise an issue, I am pleasing to raise an issue.

**Comment by lee-chase** [comment]
Closing as outdated.
