### ISSUE TITLE
The plugin doesn't work since it doesn't find a file when executing stylelint.

### ISSUE THREAD

**Issue by Mikadv** [carbon-design-system/stylelint-plugin-carbon-tokens#49]
When I install the plugin like described and launch stylelint it crashes with this:

![image](https://user-images.githubusercontent.com/49228392/136417987-3e3a4f4d-4b21-4670-b1f1-ad420b021d62.png)

Interestingly it looks like after installing files are missing that the plugin wants (in this case `carbon-components`).

I'm using `"stylelint-plugin-carbon-tokens": "^0.11.2",`

**Comment by s100** [comment]
This is a duplicate of #33.

**Comment by lee-chase** [comment]
Could you please retry @Mikadv? Recent versions (now on V2) do not construct a file path.

Closing as duplicate.
