### ISSUE TITLE
TypeError: Object.hasOwn is not a function when running git commit

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/stylelint-plugin-carbon-tokens#89]
Reference issue: https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2384

**Comment by lee-chase** [comment]
LTS for node is now 18, 16 was switched to maintenance recently https://github.com/nodejs/release#release-schedule


Node 14 is still in maintenance until April 2023.

Could change the built to target 2021. Object.hasOwn is a 2022 feature, but implemented nearly everywhere now.

http://kangax.github.io/compat-table/es2016plus/
